import "./globals.css";
import { TaskProvider } from "../context/TaskContext";
import Navbar  from '../app/components/Navbar'
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TaskProvider>
          <Navbar /> {children}</TaskProvider>
      </body>
    </html>
  );
}
